---
# tasks file for manage puppet-agent

- name: Puppet-agent install
  include_tasks: "packages/install-{{ ansible_system }}.yml"
  when: puppet_agent_install

- name: Puppet-agent configuration
  include_tasks: "configuration.yml"
  when: puppet_agent_configuration

- name: Puppet-agent service
  include_tasks: "services/service-{{ ansible_system }}.yml"
  when: puppet_agent_service_manage